---
version: '3.8'
services:
  virtualgl:
    build: .
    image: reg.growlab.digital/virtualgl
    environment:
      DISPLAY: ':0'
    ports:
      - published: 3000
        target: 22
        protocol: tcp
        mode: host
      - published: 9000
        target: 9001
        protocol: tcp
        mode: host
    volumes:
      - ~/.ssh/authorized_keys:/root/authorized_keys
      - data:/data

volumes:
  data: {}
