---
version: '3.8'
services:
  virtualgl:
    build: .
    image: ghcr.io/torresmvl/virtualgl:latest
    environment:
      DISPLAY: ':0'
    ports:
      - published: 2222
        target: 22
        protocol: tcp
        mode: host
      - published: 9001
        target: 9001
        protocol: tcp
        mode: host
    volumes:
      - ./data:/data
